Cleanup and async fw load
t-c-collab/linux pull request #15
Opened 2019-09-16 08:11 UTC by jsarha

This series drops the dependency to cdns-mhdp-common and adds asynchronous firmware loading feature needed by android boot.

The dependency to cdns-mhdp-common was cut by copying the previously shared functions to the top of the cdns-mhdp.c. The functions were changed to the slightly different register definitions on cdns-mhdp.h, instead of the duplicates on cdns-mhdp-common.h. Also the complletely untested audio functionality was removed. We should avoid changing the copied helper functions on the top so that it is easier to take a new approach for sharing code with the Rockchip driver.

2019-09-16 10:09 UTC, tomba requested changes
Drop the audio support first.

2019-09-16 10:45 UTC, tomba requested changes

2019-09-16 10:45 UTC, tomba commented on drivers/gpu/drm/bridge/cdns-mhdp.c
> +
This doesn't look like it should be part of this commit.

2019-09-16 10:45 UTC, tomba commented on drivers/gpu/drm/bridge/cdns-mhdp.c
>  		return 0;
Extra change.

2019-09-16 10:45 UTC, tomba commented on drivers/gpu/drm/bridge/cdns-mhdp.h
> +	struct mutex mutex;
It's not very clear what this protects. Everything under cnds_mhdp_device, and all the registers (except irq registers)?
Why it's not enough to protect hw_enabled and bridge_attached?

2019-09-19 09:25 UTC, jsarha commented
There is new pull request with the new version of the commits. Closing this one.

2019-09-19 09:25 UTC, closed without merging