Ti 4.19.y dp link check
t-c-collab/linux pull request #37
Opened 2019-10-07 13:44 UTC by jsarha

Link check and link status property checking.

2019-10-07 15:42 UTC, tomba requested changes

2019-10-07 15:42 UTC, tomba commented on drivers/gpu/drm/bridge/cdns-mhdp.c
> +	/* Geting event bits failed, send HPD event */
We send the HPD event in any case, so the comment doesn't quite make sense

2019-10-07 15:42 UTC, tomba commented on drivers/gpu/drm/bridge/cdns-mhdp.c
> +	/* No display reconfiguration between link check and property setting */
The comment is slightly confusing. "Prevent display reconfig between..."?

2019-10-07 15:42 UTC, tomba commented on drivers/gpu/drm/bridge/cdns-mhdp.c
> +	if (ret >= 0) {
The comment is a bit confusing here again. It says "if the read fails", but then the if() checks if it succeeded.
Maybe a single if for ret and the _ok() functions, so that the LINK_STATUS_BAD is inside the if? Well, not a biggie, but it would feel more natural to me than the "goto out" there.

2019-10-07 15:42 UTC, tomba commented on drivers/gpu/drm/bridge/cdns-mhdp.c
> +	drm_connector_set_link_status_property(conn, DRM_MODE_LINK_STATUS_BAD);
Other than the cosmetic comments above, looks good. And you're able to test this code path too? I guess you are with the analyzer.

2019-10-07 16:41 UTC, jsarha commented
On 07/10/2019 18:42, Tomi Valkeinen wrote:
> tomba requested changes on this pull request.
> 
> 
> 
>> @@ -778,6 +783,54 @@ static int load_firmware(struct cdns_mhdp_device *mhdp)
>  	return 0;
>  }
>  
> +static void mhdp_check_link(struct cdns_mhdp_device *mhdp)
> +{
> +	struct drm_connector *conn = &mhdp->connector;
> +	u8 status[DP_LINK_STATUS_SIZE];
> +	bool hpd_state;
> +	int hpd_event;
> +	int ret;
> +
> +	/* Nothing to check if there is no link */
> +	if (!mhdp->link_up)
> +		return;
> +
> +	hpd_event = cdns_mhdp_read_event(mhdp);
> +
> +	/* Geting event bits failed, send HPD event */
> 
> We send the HPD event in any case, so the comment doesn't quite make sense
> 
>> +	hpd_event = cdns_mhdp_read_event(mhdp);
> +
> +	/* Geting event bits failed, send HPD event */
> +	if (hpd_event < 0) {
> +		dev_warn(mhdp->dev, "%s: read event failed: %d\n",
> +			 __func__, hpd_event);
> +		return;
> +	}
> +
> +	hpd_state = !!(hpd_event & DPTX_READ_EVENT_HPD_STATE);
> +
> +	/* No point the check the link if HPD is down (cable is unplugged) */
> +	if (!hpd_state)
> +		return;
> +
> +	/* No display reconfiguration between link check and property setting */
> 
> The comment is slightly confusing. "Prevent display reconfig between..."?
> 
>> +	}
> +
> +	hpd_state = !!(hpd_event & DPTX_READ_EVENT_HPD_STATE);
> +
> +	/* No point the check the link if HPD is down (cable is unplugged) */
> +	if (!hpd_state)
> +		return;
> +
> +	/* No display reconfiguration between link check and property setting */
> +	mutex_lock(&conn->dev->mode_config.mutex);
> +
> +	/* Check if the link is still up */
> +	ret = drm_dp_dpcd_read_link_status(&mhdp->aux, status);
> +
> +	/* If dpcd read fails, we must assume the link is down too */
> +	if (ret >= 0) {
> 
> The comment is a bit confusing here again. It says "if the read fails", but then the if() checks if it succeeded.
> Maybe a single if for ret and the _ok() functions, so that the LINK_STATUS_BAD is inside the if? Well, not a biggie, but it would feel more natural to me than the "goto out" there.
>  

Yes, that is better. This function has gone trough so many cycles of
evolution that branches and comments are bit awkward, even if they are
"correct".

>> +	/* No display reconfiguration between link check and property setting */
> +	mutex_lock(&conn->dev->mode_config.mutex);
> +
> +	/* Check if the link is still up */
> +	ret = drm_dp_dpcd_read_link_status(&mhdp->aux, status);
> +
> +	/* If dpcd read fails, we must assume the link is down too */
> +	if (ret >= 0) {
> +		if (drm_dp_channel_eq_ok(status, mhdp->link.num_lanes) &&
> +		    drm_dp_clock_recovery_ok(status, mhdp->link.num_lanes))
> +			/* Link is Ok, no need to set link status property */
> +			goto out;
> +	}
> +
> +	/* Link is broken, so indicate it with the link status property */
> +	drm_connector_set_link_status_property(conn, DRM_MODE_LINK_STATUS_BAD);
> 
> Other than the cosmetic comments above, looks good. And you're able to test this code path too? I guess you are with the analyzer.
> 

Yes, without this patch the link systematically broken after booting up,
but with the patch the link is always reconfigured once before the
correct settings are found.

BR,
Jyri


-- 
Texas Instruments Finland Oy, Porkkalankatu 22, 00180 Helsinki.
Y-tunnus/Business ID: 0615521-4. Kotipaikka/Domicile: Helsinki

2019-10-08 07:27 UTC, jsarha commented
There is a new pull request. Closing this.

2019-10-08 07:27 UTC, closed without merging